name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Add other build steps here if necessary
      # For example, installing dependencies or building your project

  deploy:
    runs-on: ubuntu-latest
    needs: build # This ensures that the deploy job runs only after the build job completes successfully
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
